# Generated by Django 5.0.6 on 2024-05-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Generator", "0003_remove_usermaincourse_central_main_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermaincourse",
            name="central_main_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Generator.centralmaincourse",
            ),
        ),
        migrations.AddField(
            model_name="usersalad",
            name="central_salad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Generator.centralsalad",
            ),
        ),
        migrations.AddField(
            model_name="usersidedishes",
            name="central_side_dishes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Generator.centralsidedishes",
            ),
        ),
        migrations.AddField(
            model_name="usersoup",
            name="central_soup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Generator.centralsoup",
            ),
        ),
    ]
