# Generated by Django 5.0.6 on 2024-05-26 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Generator", "0004_usermaincourse_central_main_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermaincourse",
            name="central_main_course",
        ),
        migrations.RemoveField(
            model_name="usersalad",
            name="central_salad",
        ),
        migrations.RemoveField(
            model_name="usersidedishes",
            name="central_side_dishes",
        ),
        migrations.RemoveField(
            model_name="usersoup",
            name="central_soup",
        ),
    ]
