# Generated by Django 5.0.6 on 2024-05-26 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "Generator",
            "0007_rename_central_side_dishes_usersidedishes_central_side_dish",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermaincourse",
            name="central_main_course",
        ),
        migrations.RemoveField(
            model_name="usersalad",
            name="central_salad",
        ),
        migrations.RemoveField(
            model_name="usersidedishes",
            name="central_side_dish",
        ),
        migrations.RemoveField(
            model_name="usersoup",
            name="central_soup",
        ),
    ]
