# Generated by Django 5.0.6 on 2024-05-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Generator", "0010_remove_usermaincourse_central_main_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermaincourse",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersalad",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersidedishes",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersoup",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
