# Generated by Django 5.0.6 on 2024-05-30 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Generator", "0012_weeklymenu_dailymenu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermaincourse",
            old_name="last_used_at",
            new_name="last_used",
        ),
    ]
