# Generated by Django 5.0.6 on 2024-06-08 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Generator", "0015_dailymenu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="centralmaincourse",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="centralsalad",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="centralsidedishes",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="centralsoup",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="usermaincourse",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="usersalad",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="usersidedishes",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="usersoup",
            options={"ordering": ("name",)},
        ),
        migrations.AddIndex(
            model_name="centralmaincourse",
            index=models.Index(fields=["name"], name="Generator_c_name_91f0e2_idx"),
        ),
        migrations.AddIndex(
            model_name="centralsalad",
            index=models.Index(fields=["name"], name="Generator_c_name_994660_idx"),
        ),
        migrations.AddIndex(
            model_name="centralsidedishes",
            index=models.Index(fields=["name"], name="Generator_c_name_e7ac4d_idx"),
        ),
        migrations.AddIndex(
            model_name="centralsoup",
            index=models.Index(fields=["name"], name="Generator_c_name_220806_idx"),
        ),
        migrations.AddIndex(
            model_name="usermaincourse",
            index=models.Index(fields=["name"], name="Generator_u_name_924925_idx"),
        ),
        migrations.AddIndex(
            model_name="usersalad",
            index=models.Index(fields=["name"], name="Generator_u_name_f71c47_idx"),
        ),
        migrations.AddIndex(
            model_name="usersidedishes",
            index=models.Index(fields=["name"], name="Generator_u_name_75c796_idx"),
        ),
        migrations.AddIndex(
            model_name="usersoup",
            index=models.Index(fields=["name"], name="Generator_u_name_c4d413_idx"),
        ),
    ]
