# Generated by Django 5.0.6 on 2024-06-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0017_customuser_alter_centralmaincourse_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
