# Generated by Django 5.0.6 on 2024-07-04 16:09

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Generator", "0019_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersidedishes",
            options={"ordering": (django.db.models.functions.text.Lower("name"),)},
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
        ),
        migrations.AddIndex(
            model_name="usersidedishes",
            index=models.Index(fields=["name"], name="Generator_u_name_75c796_idx"),
        ),
    ]
